import json
import os

translation_map = {
    "Knight": "Cavaleiro",
    "Archers": "Arqueiras",
    "Goblins": "Goblins",
    "Giant": "Gigante",
    "P.E.K.K.A": "P.E.K.K.A",
    "Minions": "Servos",
    "Balloon": "Balão",
    "Witch": "Bruxa",
    "Barbarians": "Bárbaros",
    "Golem": "Golem",
    "Skeletons": "Esqueletos",
    "Valkyrie": "Valquíria",
    "Skeleton Army": "Exército de Esqueletos",
    "Bomber": "Bombardeiro",
    "Musketeer": "Mosqueteira",
    "Baby Dragon": "Bebê Dragão",
    "Prince": "Príncipe",
    "Wizard": "Mago",
    "Mini P.E.K.K.A": "Mini P.E.K.K.A",
    "Spear Goblins": "Goblins Lanceiros",
    "Giant Skeleton": "Esqueleto Gigante",
    "Hog Rider": "Corredor",
    "Minion Horde": "Horda de Servos",
    "Ice Wizard": "Mago de Gelo",
    "Royal Giant": "Gigante Real",
    "Guards": "Guardas",
    "Princess": "Princesa",
    "Dark Prince": "Príncipe das Trevas",
    "Three Musketeers": "Três Mosqueteiras",
    "Lava Hound": "Lava Hound",
    "Ice Spirit": "Espírito de Gelo",
    "Fire Spirit": "Espírito de Fogo",
    "Miner": "Mineiro",
    "Sparky": "Sparky",
    "Bowler": "Lançador",
    "Lumberjack": "Lenhador",
    "Battle Ram": "Aríete de Batalha",
    "Inferno Dragon": "Dragão Infernal",
    "Ice Golem": "Golem de Gelo",
    "Mega Minion": "Megasservo",
    "Dart Goblin": "Goblin com Dardo",
    "Goblin Gang": "Gangue de Goblins",
    "Electro Wizard": "Mago Elétrico",
    "Elite Barbarians": "Bárbaros de Elite",
    "Hunter": "Caçador",
    "Executioner": "Executor",
    "Bandit": "Bandida",
    "Royal Recruits": "Recrutas Reais",
    "Night Witch": "Bruxa Sombria",
    "Bats": "Morcegos",
    "Royal Ghost": "Fantasma Real",
    "Ram Rider": "Domadora de Carneiro",
    "Zappies": "Eletrocutadores",
    "Rascals": "Patifes",
    "Cannon Cart": "Carrinho de Canhão",
    "Mega Knight": "Megacavaleiro",
    "Skeleton Barrel": "Barril de Esqueletos",
    "Flying Machine": "Máquina Voadora",
    "Wall Breakers": "Destruidores de Muros",
    "Royal Hogs": "Porcos Reais",
    "Goblin Giant": "Goblin Gigante",
    "Fisherman": "Pescador",
    "Magic Archer": "Arqueiro Mágico",
    "Electro Dragon": "Dragão Elétrico",
    "Firecracker": "Pirotécnica",
    "Mighty Miner": "Grande Mineiro",
    "Super Witch": "Super Bruxa",
    "Elixir Golem": "Golem de Elixir",
    "Battle Healer": "Curadora Guerreira",
    "Skeleton King": "Rei Esqueleto",
    "Super Lava Hound": "Super Lava Hound",
    "Super Magic Archer": "Super Arqueiro Mágico",
    "Archer Queen": "Rainha Arqueira",
    "Santa Hog Rider": "Papai Noel Corredor",
    "Golden Knight": "Cavaleiro Dourado",
    "Super Ice Golem": "Super Golem de Gelo",
    "Monk": "Monge",
    "Super Archers": "Super Arqueiras",
    "Skeleton Dragons": "Dragões Esqueletos",
    "Terry": "Terry",
    "Super Mini P.E.K.K.A": "Super Mini P.E.K.K.A",
    "Mother Witch": "Bruxa Mãe",
    "Electro Spirit": "Espírito Elétrico",
    "Electro Giant": "Gigante Elétrico",
    "Raging Prince": "Príncipe Furioso",
    "Phoenix": "Fênix",
    "Cannon": "Canhão",
    "Goblin Hut": "Cabana de Goblins",
    "Mortar": "Morteiro",
    "Inferno Tower": "Torre Inferno",
    "Bomb Tower": "Torre de Bombas",
    "Barbarian Hut": "Cabana de Bárbaros",
    "Tesla": "Tesla",
    "Elixir Collector": "Coletor de Elixir",
    "X-Bow": "X-Besta",
    "Tombstone": "Lápide",
    "Furnace": "Fornalha",
    "Goblin Cage": "Jaula de Goblins",
    "Goblin Drill": "Escavadeira de Goblins",
    "Party Hut": "Cabana de Festa",
    "Fireball": "Bola de Fogo",
    "Arrows": "Flechas",
    "Rage": "Fúria",
    "Rocket": "Foguete",
    "Goblin Barrel": "Barril de Goblins",
    "Freeze": "Gelo",
    "Mirror": "Espelho",
    "Lightning": "Relâmpago",
    "Zap": "Choque",
    "Poison": "Veneno",
    "Graveyard": "Cemitério",
    "The Log": "O Tronco",
    "Tornado": "Tornado",
    "Clone": "Clone",
    "Earthquake": "Terremoto",
    "Barbarian Barrel": "Barril de Bárbaro",
    "Heal Spirit": "Espírito Curador",
    "Giant Snowball": "Bola de Neve Gigante",
    "Royal Delivery": "Encomenda Real",
    "Party Rocket": "Foguete de Festa"
}

def translate():
    base_dir = os.path.dirname(__file__)
    file_path = os.path.join(base_dir, 'cards.json')
    
    with open(file_path, 'r', encoding='utf-8') as f:
        cards = json.load(f)
        
    for card in cards:
        if card['name'] in translation_map:
            card['name'] = translation_map[card['name']]
            
    with open(file_path, 'w', encoding='utf-8') as f:
        json.dump(cards, f, ensure_ascii=False, indent=4)
        
    print("Traduzido com sucesso!")

if __name__ == "__main__":
    translate()
