# palavras.py
# Lista de palavras que o jogo da forca pode escolher aleatoriamente.

lista_palavras = [
    "python",
    "programacao",
    "internet",
    "forca",
    "algoritmo",
    "matematica",
    "computador",
    "teclado",
    "monitor",
    "valentim",
    "veyon",
    "bancodedados",
    "java",
    "c",
    "portugol",
    "desenvolvimento",
    "software",
    "hardware",
    "rede",
    "sistema",
    "linguagem",
    "debugging",
    "compilador",
    "framework",
    "api",
    "interface",
    "variavel",
    "função",
    "loop",
    "condicional", 
    "array",
    "string",
    "boolean",
    "classe",
    "webdesign",
    "mobile",
    "jogos",
    "aplicativo",
    "tecnologia",
    "inovacao",
    "futuro",
    "educacao",
    "ciencia",
    "engenharia",
    "robotica",
    "inteligenciaartificial",
    "machinelearning",
    "bigdata",
    "cloudcomputing",
    "seguranca",
    "criptografia",
    "blockchain",
    "realidadevirtual",
    "realidadeaumentada",
    "internetdascoisas",
    "automacao",
    "drone",
    "biometria",
    "nanotecnologia",
    "quantumcomputing",
    "ciberseguranca",
    

]